### PR TITLE
Upgrades symfony-console

### PR DESCRIPTION
**Pull request by jbrooksuk**
If you want to use `poser` in a modern project (such as Laravel 5) you need this.

### CODE REVIEW

**Comment by garak** [comment]
This should be `~2.0|~3.0`, you cannot drop support for previous Symfony version just like that.

**Comment by liuggio** [comment]
Hi @jbrooksuk 
thanks for the PR,
the tests are red :( 
can you please add `~2.0|~3.0` instead forcing to `3.0`?

**Comment by jbrooksuk** [comment]
> This should be ~2.0|~3.0, you cannot drop support for previous Symfony version just like that.

That's what Semver is for ;)

**Comment by jbrooksuk** [comment]
Fixing this.

**Comment by jbrooksuk** [comment]
Fixed.

**Comment by liuggio** [comment]
@jbrooksuk great!
 @garak any hint how to solve dependency problem on CI?

**Comment by jmleroux** [comment]
To be closed, already merged.

**Pull request closed without merging**
